type Customer {
	_id: ID!
	name: String!
	phone: String!
	cpf: String!
	birthday: String!
}

input CustomerInput {
	name: String!
	phone: String!
	cpf: String!
	birthday: String!
}

type Query {
	customers: [Customer!]!
	customer(id: ID!): Customer
}

type Mutation {
	createCustomer(data: CustomerInput): Customer!
}
